# Generated by Django 3.0.7 on 2020-07-12 22:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=111, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 1, 3, 58, 605910)),
        ),
        migrations.AlterField(
            model_name='orderitemmodel',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='store.ProductModel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.FloatField(),
        ),
    ]
