# Generated by Django 3.0.7 on 2020-07-01 13:42

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='SKU',
            field=models.CharField(default='aa', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='main_image',
            field=models.ImageField(upload_to=store.models.get_image_subdirectory_for_item_images),
        ),
    ]
