# Generated by Django 3.0.7 on 2020-07-12 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200713_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemmodel',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 1, 5, 12, 919777)),
        ),
    ]
