# Generated by Django 3.0.7 on 2020-07-13 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200713_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='digital',
            new_name='is_digital',
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 19, 3, 25, 139181)),
        ),
    ]
