# Generated by Django 3.0.7 on 2020-07-17 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200713_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemmodel',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 21, 8, 59, 948308)),
        ),
    ]
