# Generated by Django 3.0.7 on 2020-07-19 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200717_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='SKU',
            new_name='sku',
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 14, 50, 32, 64060)),
        ),
    ]
