# Generated by Django 3.0.7 on 2020-07-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200703_1843'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(complete=False), fields=('user',), name='one_non_completed_order'),
        ),
    ]
