# Generated by Django 3.0.7 on 2020-07-20 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200719_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 15, 1, 35, 380500)),
        ),
    ]
